### ISSUE TITLE
Create a SCC for openshift 

### ISSUE THREAD

**Issue by harche** [openshift/instaslice-operator#127]
In order to run on Openshift, a scc and rolebinding must be created. Initial testing suggests following scc works, but it needs more tightened capabilities. 

```yaml
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: instaslice-operator-scc
allowPrivilegedContainer: true 
allowedCapabilities:
- "ALL"
allowPrivilegeEscalation: true 
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
readOnlyRootFilesystem: false
```
and the corresponding role binding, 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: use-scc-instaslice-operator
subjects:
- kind: ServiceAccount
  name: instaslice-operator-controller-manager
  namespace: instaslice-operator-system
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:instaslice-operator-scc
  apiGroup: rbac.authorization.k8s.io
```

**Comment by harche** [comment]
```yaml
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: instaslice-operator-scc
allowPrivilegedContainer: true 
allowedCapabilities:
- "NET_ADMIN"
- "SYS_ADMIN"
- "SYS_TIME"
allowPrivilegeEscalation: true 
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
readOnlyRootFilesystem: false
```
worked too.
