### ISSUE TITLE
Consider eliminating MIG resource requests/limits and MIG capacity changes

### ISSUE THREAD

**Issue by tardieu** [openshift/instaslice-operator#143]
InstaSlice is controlling the pod placement (via `org.instaslice` resources or possibly node selectors), the MIG slice attribution to the container (via the injection of the `NVIDIA_VISIBLE_DEVICES` env variable into the container spec), as well as the timing of the deployment of the pod (via its scheduling gate). Therefore, there is no need for the scheduler and the kubelet to account for MIG resources such as `nvidia.com/mig-1g.5gb`. For instance, a pod spec such as the following will be scheduled and running on its intended MIG slice even with the MIG resource limit commented out:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: vectoradd
    image: "quay.io/tardieu/vectoradd:0.1.0"
    resources:
       limits:
        org.instaslice/17b63565-c7a8-489d-8491-d9a165ad4745: 1
#        nvidia.com/mig-1g.5gb: 1
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: MIG-a8b44796-6f4a-5042-bcc8-d7648b083592
```

1. Dynamically controlling the MIG slice capacity of the node is therefore unecessary. Moreover, we have observed in practice that dynamically modifying the node capacity (capacity and/or allocatable capacity) is slow and brittle leading to recurring pod scheduling failures.

2. Overriding the MIG slice capacity of the node even just once, for instance at InstaSlice startup time, is also fundamentally brittle as this capacity is normally managed by the GPU operator. We have no guarantee at this point that any update we would make to this capacity will not eventually create a conflict with the GPU operator or a subsequent release of the GPU operator.

As a result, we should consider:
- deleting the MIG resource requests and limits from the container spec in the InstaSlice webhook,
- eliminating the MIG node capacity adjustment from the InstaSlice code altogether.

By combining this change with #101, we can completely eliminate dynamic node capacity adjustments making InstaSlice more robust and significantly faster.
