### ISSUE TITLE
Implement namespace selector for pod webhook

### ISSUE THREAD

**Issue by tardieu** [openshift/instaslice-operator#93]
Pod webhooks have the potential to block pod admission, causing hard deadlocks if faulty or misconfigured. Other projects leveraging pod webhooks such as Kueue support scoping their pod webhooks to specific namespaces. See for example https://kueue.sigs.k8s.io/docs/tasks/run/plain_pods/.
```yaml
  podOptions:
    # You can change namespaceSelector to define in which 
    # namespaces kueue will manage the pods.
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values: [ kube-system, kueue-system ]
```
We should consider implementing such a namespace selector capability in InstaSlice.
